# Самый первый плагин Богдана Турова
# Разработчик Богдан Туров
# Ссылка на вк Богдана Турова - vk.com/mblodeec
# С вами был Богдан Туров

join: 
  actionbar: 'Ты зашел на сервер §a§lGriefYou'    
  title: '§a§lGRIEFYOU'    
  subtitle: '§fУспешный вход на сервер!'    
  text: |
    §f           §7§l⚔ §a§lＧｒｉｅｆ§f§lＹｏｕ §7§l⚔
    §r  §r 
    §f      §fДобро пожаловать §fна наш §fсервер!
    §r  §r  
    §f     §fУ нас разрешен §e§lГРИФ§f любым способом
    §f  §fБесплатный §c§l⚷ кейс§f с донатом - §e/getcase
    §r  §r 

whois:
  0: '§7'  
  1: '§7[§6§СЕРВЕР§7] §fИнформация о игроке'
  2: '§f'
  3: '§6| §fНикнейм §e'
  4: '§6| §fIp-адрес §e'
  5: '§6| §fУбийств §e'
  6: '§6| §fСмертей §e'
  7: '§6| §fНаиграно времени §e'  
  8: '§6'

messages:
  onlyplayers: '§7[§6§lСЕРВЕР§7] §fЭта команда только для игроков'
  playernofound: '§7[§6§lСЕРВЕР§7] §fТакого игрока нет на сервере'
  nopermission: '§7[§6§lСЕРВЕР§7] §fУ вас недостаточно прав'
  setcreative: '§7[§6§lСЕРВЕР§7] §fВы установили режим §aКреатив'
  setsurvival: '§7[§6§lСЕРВЕР§7] §fВы установили режим §aВыживание'
  setadventure: '§7[§6§lСЕРВЕР§7] §fВы установили режим §aПриключения'
  setspectator: '§7[§6§lСЕРВЕР§7] §fВы установили режим §aНаблюдатель'
  heal: '§7[§6§lСЕРВЕР§7] §fВы восстановили здоровье'
  healother: '§7[§6§lСЕРВЕР§7] §fВы восстановили здоровье игроку §e{heal_player}'
  feed: '§7[§6§lСЕРВЕР§7] §fВы восстановили голод'
  feedother: '§7[§6§lСЕРВЕР§7] §fВы восстановили голод игроку §e{feed_player}'
  setday: '§7[§6§lСЕРВЕР§7] §fВы установили §eДень §fв мире §a{world}'
  setnight: '§7[§6§lСЕРВЕР§7] §fВы установили §eНочь §fв мире §a{world}'
  storm: '§7[§6§lСЕРВЕР§7] §fВы установили §eДождевую погоду §fв мире §a{world}'
  thunder: '§7[§6§lСЕРВЕР§7] §fВы установили §eГромовую погоду §fв мире §a{world}'
  clear: '§7[§6§lСЕРВЕР§7] §fВы установили §eЯсную погоду §fв мире §a{world}'